vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        indexImageFile:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/imgUpload'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer